travis:
  secure:
    BINSTAR_TOKEN: JyXuYOJ3cc6XTR6ZRPVh3V7RKLuUodPIPcflId7spv8gDVDQVNLWoDZrq0vWoVJp8mhIkAfQZJS22V4S4AHolWiW5xPKsIZr4ijo8V0w8u89O6Ewdafy1EC/Op6Z5nNvExjoDEvZqhRBRKLDPMg2uEa9SBuyXpF+GzA95MxQzHsSGXaNxN9JwSz5Pgi5A3QobDpxJQnzesssp/xUyc1RNLp4NBviNqwl1BYZKJEl05vn6xf2NBlmLzzCO3Z7MMfJrNQ3wEdAjCe+0yoGmNo5y0EDFtTfwnDyrVaWU9I7XuaKCIU1L7iSWlU5z+VWT1L8BwMscV9Uojzh44A1WlmiVBzynlHyFCjJOk7X1AthyWummOkyAoqaAjRKjnevEzeNWozpN0Nk9HgCffrctEYkCtlQgqS5DA7DVkTnk/B4/L1EoAe/KrB/D/R8w3ZU4L5LoXZiOFydYLw/QHnPMCbhwbET94w/AtRoQPfPQtK1y/S1pl4HO8sKPMd76K+vneq8GVLQYZzYQe5OW+EAyy11S89bdCTAata1qoF+EVfLhLz5gJX4dPP9zTZKnEQmwGxX4KLj9xPkTuxfImC9xsGRpZTNj02hkj1WXnGBmxpL3RUV53RL+UiG/OMAA7gwXNpda91DMoT4Lg1t/Kjvt3swkGgtIvgTMq4SSwBC5RbUubE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
